tiles: "OSM"

data_dir: "./data"

scenario_names:
  # NG: Nigeria
  # NG_no_oil: Nigeria without oil
  # MA: Morocco

  rigid: Rigid Scenario
  flex: Flexible Scenario
  flex_upd: Updated Flexible Scenario  

  # BJ_4: Benin four clusters
  # BJ_6: Benin six clusters
  # NG_BJ_6: Nigeria ad Benin

  # results_2011: Case A
  # results_2013: Case B
  # results_2018: Case C

  # GE: GE

######### time-series keys

gen_t_parameter:
  p:
    nice_name: Supply
    unit: MW
    legend_title: " "
  p_max_pu:
    nice_name: Maximum Output Possible Per Unit Nominal Power
    unit: MW
    legend_title: " "

loads_t_parameter:
  p: 
    nice_name: Demand
    unit: MW
    legend_title: " "

links_t_parameter:
  p0:
    nice_name: Demand
    unit: MW
    legend_title: " "
  p1:
    nice_name: Another Demand
    unit: MW
    legend_title: " " 
  p2:
    nice_name: Heat Demand
    unit: MW
    legend_title: " "        

######### operation parameters

operation:
  carrier:
    total-electricity: Total Electricity
    total-heat: Total Heating
    H2: Hydrogen
    gas: Methane
    total-liquid-hydrocarbons: Liquid Hydrocarbons
    co2 stored: Stored Carbon Dioxide
    co2: Carbon Dioxide
    # AC: High Voltage Electricity
    # low voltage: Low Voltage Electricity
    # urban central heat: Urban Central Heating
    # residential rural heat: Residential Rural Building Heating
    # methanol: Methanol
    # oil: Liquid Hydrocarbons
  resolution:
    24H: daily
    168H: weekly

scenarios:
  costs: Total System Costs (bn€/a)
  generation: Generation Capacities (GW)
  storage: Storage Capacities (TWh)
  conversion: Conversion Capacities (GW)
  energy: Energy Balance (TWh/a)
  co2: Carbon Dioxide Balance (MtCO2/a)
  # hydrogen: Hydrogen Balance (TWh/a)

ylim:
  costs: [0, 1000]
  generation: [0, 7000]
  storage: [0, 200]
  conversion: [0, 11000]
  energy: [-15000, 15000]
  co2: [-600, 600]

countries_names:
  AL: Albania
  AT: Austria
  BA: Bosnia & Herzegovina
  BE: Belgium
  BG: Bulgaria
  CH: Switzerland
  CZ: Czechia
  DE: Germany
  DK: Denmark
  EE: Estonia
  ES: Spain
  FI: Finland
  FR: France
  GB: United Kingdom
  GR: Greece
  HR: Croatia
  HU: Hungary
  IE: Ireland
  IT: Italy
  LT: Lithuania
  LU: Luxembourg
  LV: Latvia
  ME: Montenegro
  MK: North Macedonia
  NL: Netherlands
  NO: Norway
  PL: Poland
  PT: Portugal
  RO: Romania
  RS: Serbia
  SE: Sweden
  SI: Slovenia  

########## spatial parameters

spatial_parameters:
  p_nom_opt:
    nice_name: Capacity
    unit: (MW)  
  cf:
    nice_name: Capacity Factor
    unit: "%"
  crt:
    nice_name: Curtailment
    unit: "%"
  usdpt:
    nice_name: Used Potential
    unit: "%"       
  marginal_cost:
    nice_name: Cost During Production
    unit: (euro/MWh)
  capital_cost:
    nice_name: Cost Of Expanding Generation
    unit: (euro/MW)
  bus_load:
    nice_name: Electricity Load
    unit: (MW)    

network_parameters:
  total_capacity: Total Capacity (MVA)
  reinforcement: Reinforcement (MVA)
  original_capacity: Original Capacity (MVA)
  max_capacity: Maximum Capacity (MVA)
  length: Line Length (km)

carrier:
  # power
  onwind: Onshore Wind
  offwind-ac: Offshore Wind (AC)
  offwind-dc: Offshore Wind (DC)
  # names conflict with solat thermal
  solar: solar
  solar rooftop: Solar Rooftop
  hydro: Reservoir & Dam
  ror: Run of River
  gas: Gas

  industry electricity: El Industry
  gas for industry: Gas Industry
  # H2 for industry is captured as "for industry"
  for industry: H2 Industry
  low-temperature heat for industry: LT Heat Industry

  solid biomass for industry: Solid Bio Industry
  land transport EV: El Vehicles
  process emissions: Process Emission
  EU naphtha for industry: Naphta Industry

  urban central heat: UrbCenOvr Heating
  residential urban decentral heat: UrbDecRes Heating
  services urban decentral heat: UrbDecSer Heating
  residential rural heat: RurDecRes Heating
  services rural heat: RurDecSer Heating

  EU oil: Oil
  land transport fuel cell: FC Vehicles  
  EU kerosene for aviation: Avia Kerosene
  EU shipping methanol: Methanol Shipping  

  # heat
  urban central solar thermal collector: Solar Thermal (UrbCenOvr)
  residential urban decentral solar thermal collector: Solar Thermal (UrbDecRes)
  services urban decentral solar thermal collector: Solar Thermal (UrbDecSer)
  residential rural solar thermal collector: Solar Thermal (RurDecRes)
  services rural solar thermal collector: Solar Thermal (RurDecSer)

  # retrofitting

  # moderate
  retrofitting moderate urban central heat: Retrofit Moder (UrbCenOvr)
  retrofitting moderate residential urban decentral heat: Retrofit Moder (UrbDecRes)
  retrofitting moderate services urban decentral heat: Retrofit Moder (UrbDecSer)
  retrofitting moderate residential rural heat: Retrofit Moder (RurDecRes)
  retrofitting moderate services rural heat: Retrofit Moder (RurDecSer)

  # ambitious
  retrofitting ambitious urban central heat: Retrofit Ambit (UrbCenOvr)
  retrofitting ambitious residential urban decentral heat: Retrofit Ambit (UrbDecRes)
  retrofitting ambitious services urban decentral heat: Retrofit Ambit (UrbDecSer)
  retrofitting ambitious residential rural heat: Retrofit Ambit (RurDecRes)
  retrofitting ambitious services rural heat: Retrofit Ambit (RurDecSer)

  power: Power
  services rural resistive heater: services rural resistive heater
  process emissions: process emissions
  urban central solid biomass CHP: urban central solid biomass CHP
  Fuel Cell: Fuel Cell
  electricity distribution grid: electricity distribution grid
  urban central solid biomass CHP CC: urban central solid biomass CHP CC
  EU process emissions CC: EU process emissions CC
  solid biomass for industry CC: solid biomass for industry CC
  battery discharger: battery discharger
  services urban decentral water tanks dischar: services urban decentral water tanks dischar
  residential urban decentral micro gas CHP: residential urban decentral micro gas CHP
  SMR CC: SMR CC
  residential rural water tanks discharger: residential rural water tanks discharger
  residential urban decentral air heat pump: residential urban decentral air heat pump
  urban central DAC: urban central DAC
  urban central gas CHP CC: urban central gas CHP CC
  services rural ground heat pump: services rural ground heat pump
  Fischer-Tropsch: Fischer-Tropsch
  residential urban decentral water tanks char: residential urban decentral water tanks char
  OCGT: OCGT
  services rural gas boiler: services rural gas boiler
  gas for industry: gas for industry
  residential urban decentral water tanks disc: residential urban decentral water tanks disc
  G: G
  residential urban decentral resistive heater: residential urban decentral resistive heater
  residential rural resistive heater: residential rural resistive heater
  biogas to gas: biogas to gas
  services rural water tanks discharger: services rural water tanks discharger
  residential rural water tanks charger: residential rural water tanks charger
  urban central gas boiler: urban central gas boiler
  residential rural gas boiler: residential rural gas boiler
  urban central air heat pump: urban central air heat pump
  services rural micro gas CHP: services rural micro gas CHP
  EU shipping methanol: EU shipping methanol
  services urban decentral water tanks charger: services urban decentral water tanks charger
  Electrolysis: Electrolysis
  SMR: SMR
  urban central water tanks discharger: urban central water tanks discharger
  residential rural micro gas CHP: residential rural micro gas CHP
  home battery discharger: home battery discharger
  services urban decentral resistive heater: services urban decentral resistive heater
  services urban decentral gas boiler: services urban decentral gas boiler
  residential rural ground heat pump: residential rural ground heat pump
  residential urban decentral gas boiler: residential urban decentral gas boiler
  services urban decentral DAC: services urban decentral DAC
  urban central gas CHP: urban central gas CHP
  methanolisation: methanolisation
  -reversed: -reversed
  ervices urban decentral micro gas CHP: ervices urban decentral micro gas CHP
  olid biomass for industry: olid biomass for industry
  U naphtha for industry: U naphtha for industry
  attery charger: attery charger
  as for industry CC: as for industry CC
  rban central water tanks charger: rban central water tanks charger
  abatier: abatier
  ome battery charger: ome battery charger
  rban central resistive heater: rban central resistive heater
  U kerosene for aviation: U kerosene for aviation
  ervices urban decentral air heat pump: ervices urban decentral air heat pump
  ervices rural water tanks charger: ervices rural water tanks charger
  EV charger: EV charger

  # biomass: Biomass  
  # CCGT: Combined-Cycle Gas
  # OCGT: Open-Cycle Gas     
  # geothermal: Geothermal
  # coal: Coal
  # oil: Oil
  # nuclear: Nuclear
  # onwind: Onshore Wind
  # lignite: Lignite
  # hydro: Reservoir & Dam
  # PHS: Pumped Hydro Storage
  # H2: Hydrogen Storage
  # battery: Battery Storage
  # load: Load


# https://holoviews.org/user_guide/Colormaps.html
# you can also pick you own colors
carrier_colors:
  CCGT: Purples
  oil: Greys
  solar: YlOrBr
  onwind: Blues
  ror: BuPu
  OCGT: Oranges
  coal: PuBuGn
  biomass: Reds
  offwind-ac: Reds
  geothermal: Reds
  nuclear: Reds
  offwind-dc: Reds
  lignite: Reds
  hydro: Reds
  PHS: Reds
  H2: Reds
  battery: Reds


########### SCENARIO COMPARISION parameters

statistics_param_units:
  Capacity Factor: Capacity factor, %
  Capital Expenditure: Euro
  Curtailment: MW
  Installed Capacity: MW
  Operational Expenditure: Euro
  Optimal Capacity: MW
  Revenue: Euro
  Supply: MW-hours
  Withdrawal: Euro

second_param_units:
  CO2 emissions: MtCO2
  # TODO Would be worth discussing which parameter does make sense as a second option
  # strictly speaking, we have Optimal Capacity in the droplist above
  # but agree that it may be worth to have a visual comparison
  Optimal Capacity: MW

tech_colors:
  # wind
  onwind: "#235ebc"
  onshore wind: "#235ebc"
  offwind: "#6895dd"
  offshore wind: "#6895dd"
  offwind-ac: "#6895dd"
  offshore wind (AC): "#6895dd"
  offwind-dc: "#74c6f2"
  offshore wind (DC): "#74c6f2"
  # water
  hydro: "#298c81"
  hydro reservoir: "#298c81"
  ror: "#3dbfb0"
  run of river: "#3dbfb0"
  hydroelectricity: "#298c81"
  PHS: "#51dbcc"
  wave: "#a7d4cf"
  geothermal: "gray"
  # solar
  solar: "#f9d002"
  solar PV: "#f9d002"
  solar thermal: "#ffbf2b"
  solar rooftop: "#ffea80"
  # gas
  OCGT: "#e0986c"
  OCGT marginal: "#e0986c"
  OCGT-heat: "#e0986c"
  gas boiler: "#db6a25"
  gas boilers: "#db6a25"
  gas boiler marginal: "#db6a25"
  gas: "#e05b09"
  fossil gas: "#e05b09"
  natural gas: "#e05b09"
  CCGT: "#a85522"
  CCGT marginal: "#a85522"
  gas for industry co2 to atmosphere: "#692e0a"
  gas for industry co2 to stored: "#8a3400"
  gas for industry: "#853403"
  gas for industry CC: "#692e0a"
  gas pipeline: "#ebbca0"
  gas pipeline new: "#a87c62"
  # oil
  oil: "#c9c9c9"
  oil boiler: "#adadad"
  agriculture machinery oil: "#949494"
  agriculture machinery: "#abdeff"
  shipping oil: "#808080"
  land transport oil: "#afafaf"
  # nuclear
  Nuclear: "#ff8c00"
  Nuclear marginal: "#ff8c00"
  nuclear: "#ff8c00"
  uranium: "#ff8c00"
  # coal
  Coal: "#545454"
  coal: "#545454"
  Coal marginal: "#545454"
  solid: "#545454"
  Lignite: "#826837"
  lignite: "#826837"
  Lignite marginal: "#826837"
  # biomass
  biogas: "#e3d37d"
  biogas upgrading: "#e3d37d"
  biomass: "#baa741"
  solid biomass: "#baa741"
  solid biomass CHP: "#9d9042"
  solid biomass transport: "#baa741"
  solid biomass for industry: "#7a6d26"
  solid biomass for industry CC: "#47411c"
  solid biomass CHP CC: "#aeb841"
  solid biomass for industry co2 from atmosphere: "#736412"
  solid biomass for industry co2 to stored: "#47411c"
  # demand
  load: "#c94a4a"
  # power transmission
  lines: "#6c9459"
  transmission lines: "#6c9459"
  electricity distribution grid: "#97ad8c"
  # electricity demand
  Electric load: "#110d63"
  electric demand: "#110d63"
  electricity: "#110d63"
  industry electricity: "#2d2a66"
  industry new electricity: "#2d2a66"
  agriculture electricity: "#494778"
  agriculture: "#494778"
  # battery + EVs
  battery: "#ace37f"
  pbattery: "#ace37f"
  nbattery: "#ace37f"
  battery storage: "#ace37f"
  home battery: "#80c944"
  home battery storage: "#80c944"
  BEV charger: "#baf238"
  V2G: "#e5ffa8"
  land transport EV: "#baf238"
  Li ion: "#baf238"
  # hot water storage
  water tanks: "#e69487"
  hot water storage: "#e69487"
  hot water charging: "#0000ff"
  hot water discharging: "#0000ff"
  # heat demand
  Heat load: "#cc1f1f"
  heat: "#cc1f1f"
  heat demand: "#cc1f1f"
  rural heat: "#ff5c5c"
  residential rural heat: "#276419" #"#ff7c7c"
  services rural heat: "#99095c" #"#ff9c9c"
  urban central heat: "#7704c9"
  residential urban decentral heat: "#93c75b" 
  services urban decentral heat: "#e797c4"
  central heat: "#cc1f1f"
  decentral heat: "#750606"
  low-temperature heat for industry: "#8f2727"
  process heat: "#ff0000"
  agriculture heat: "#d9a5a5"
  # heat supply
  heat pumps: "#2fb537"
  heat pump: "#2fb537"
  air heat pump: "#36eb41"
  ground heat pump: "#2fb537"
  Ambient: "#98eb9d"
  gas CHP: "#8a5751"
  CHP: "#8a5751"
  gas CHP CC: "#634643"
  CHP CC: "#634643"
  CHP heat: "#8a5751"
  CHP electric: "#8a5751"
  district heating: "#e8beac"
  resistive heater: "#d8f9b8"
  retrofitting: "#8487e8"
  building retrofitting: "#8487e8"
  # hydrogen
  H2 for industry: "#f073da"
  H2 for shipping: "#ebaee0"
  H2: "#bf13a0"
  pH2: "#bf13a0"
  nH2: "#bf13a0"   
  hydrogen: "#bf13a0"
  SMR: "#870c71"
  SMR CC: "#4f1745"
  steam methane reforming: "#870c71"
  steam methane reforming CC: "#4f1745"
  H2 liquefaction: "#d647bd" 
  hydrogen storage: "#bf13a0"
  H2 storage: "#bf13a0"
  land transport fuel cell: "#6b3161"
  H2 pipeline: "#f081dc"
  H2 pipeline retrofitted: "#ba99b5"
  H2 Fuel Cell: "#c251ae"
  H2 Electrolysis: "#ff29d9"
  power-to-hydrogen: "#ff29d9"
  # syngas
  Sabatier: "#9850ad"
  methanation: "#c44ce6"
  methane: "#c44ce6"
  helmeth: "#e899ff"
  # synfuels
  Fischer-Tropsch: "#25c49a"
  liquid: "#25c49a"
  kerosene for aviation: "#a1ffe6"
  aviation fuels: "#a1ffe6"
  naphtha for industry: "#57ebc4"
  methanolisation: "#83d6d5"
  methanol: "#468c8b"
  shipping methanol: "#468c8b"
  shipping fuels: "#468c8b"
  shipping methanol emissions: "#468c8b"
  methanol emissions: "#468c8b"
  # co2
  CC: "#f29dae"
  carbon capture: "#f29dae"
  CCS: "#f29dae"
  CO2 sequestration: "#f29dae"
  DAC: "#ff5270"
  direct air capture: "#ff5270"
  co2 stored: "#f2385a"
  co2: "#f29dae"
  co2 vent: "#ffd4dc"
  CO2 pipeline: "#f5627f"
  # emissions
  process emissions CC: "#000000"
  process emissions: "#222222"
  process emissions to stored: "#444444"
  process emissions to atmosphere: "#888888"
  oil emissions: "#aaaaaa"
  liquid hydrocarbons emissions: "#aaaaaa"
  shipping oil emissions: "#555555"
  land transport oil emissions: "#777777"
  agriculture machinery oil emissions: "#333333"
  # other
  shipping: "#03a2ff"
  power-to-heat: "#2fb537"
  power-to-gas: "#c44ce6"
  power-to-H2: "#ff29d9"
  power-to-liquid: "#25c49a"
  gas-to-power/heat: "#ee8340"
  waste: "#e3d37d"
  other: "#000000"
  import pipeline-h2: "#fff6e0"
  import shipping-lh2: "#ebe1ca"
  import shipping-lch4: "#d6cbb2"
  import shipping-ftfuel: "#bdb093"
  import hvdc: "#91856a"
  fossil oil and gas: "#ababab"
  green e-fuel imports: "#03a2ff"
preferred_order:
  - H2 storage
  - hydrogen storage
  - battery storage
  - BEV charger
  - V2G
  - hot water storage
  - co2
  - hydroelectricity
  - hydro reservoir
  - pumped hydro storage
  - run of river
  - transmission lines
  - electricity distribution grid
  - solid biomass
  - biogas
  - onshore wind
  - offshore wind
  - offshore wind (AC)
  - offshore wind (DC)
  - solar PV
  - solar thermal
  - solar rooftop
  - solar
  - building retrofitting" "ground heat pump
  - air heat pump
  - heat pump
  - resistive heater
  - power-to-heat
  - gas-to-power/heat
  - CHP
  - OCGT
  - gas boiler
  - gas
  - natural gas
  - helmeth
  - methanation
  - power-to-gas
  - power-to-H2
  - H2 pipeline
  - H2 pipeline retrofitted
  - gas pipeline
  - gas pipeline new
  - H2 liquefaction
  - power-to-liquid
  - CO2 sequestration
  - CCS  
